### ISSUE TITLE
Conexión de Datos 

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-companion-ai#1]
[CONEXION_A_LA_BASE_DE_DATOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-companion-ai/files/15487835/CONEXION_A_LA_BASE_DE_DATOS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Calificacion 19
